# lang_map.py
# Mapping of FLORES‑200 / fastText language codes → human‑readable names

lang_map = {
    "ace_Arab": "Acehnese (Arabic script)",
    "afr_Latn": "Afrikaans",
    "arb_Arab": "Modern Standard Arabic",
    "azb_Arab": "South Azerbaijani (Arabic script)",
    "azj_Latn": "North Azerbaijani (Latin script)",
    "ben_Beng": "Bengali",
    "bjn_Arab": "Banjar (Arabic script)",
    "bjn_Latn": "Banjar (Latin script)",
    "bod_Tibt": "Tibetan (Standard Tibetan)",
    "bxr_Cyrl": "Buryat (Cyrillic script)",
    "deu_Latn": "German",
    "eng_Latn": "English",
    "fra_Latn": "French",
    "glg_Latn": "Galician",
    "hin_Deva": "Hindi",
    "ind_Latn": "Indonesian",
    "kor_Hang": "Korean (Hangul)",
    "lmo_Latn": "Lombard (Latin script)",
    "mai_Deva": "Maithili",
    "npi_Deva": "Nepali",
    "oci_Latn": "Occitan",
    "pbt_Arab": "Pashto (Arabic script)",
    "pes_Arab": "Persian (Farsi, Arabic script)",
    "prs_Arab": "Dari Persian (Arabic script)",
    "snd_Arab": "Sindhi (Arabic script)",
    "spa_Latn": "Spanish",
    "swh_Latn": "Swahili (Latin script)",
    "tso_Latn": "Tsonga (Latin script)",
    "urd_Arab": "Urdu (Arabic script)",
    "vie_Latn": "Vietnamese (Latin script)",
    "yue_Hant": "Cantonese (Traditional Chinese script)",
    "zsm_Latn": "Malay (Latin script)",
    # Additional codes added:
    "bak_Cyrl": "Bashkir",
    "rus_Cyrl": "Russian",
    "amh_Ethi": "Amharic",
    "jpn_Jpan": "Japanese",
    "pan_Guru": "Panjabi",
    "uig_Arab": "Uyghur (Arabic script)",
    "prs_Arab": "Dari Persian (Arabic script)",  # duplicate mapping
    "pbt_Arab": "Pashto (Arabic script)",         # duplicate mapping
    "knc_Arab": "Central Kurdish (Arabic script)",
    "zsm_Latn": "Malay (Latin script)",          # duplicate mapping
    "sun_Latn": "Sundanese (Latin script)",
    "asm_Beng": "Assamese",
    "mar_Deva": "Marathi",
    "pcm_Latn": "Nigerian Pidgin",
    "kas_Arab": "Kashmiri (Arabic script)",
    "mai_Deva": "Maithili",                       # duplicate mapping
    "mni_Beng": "Meitei (Bengali script)",
    # … you can continue adding other codes you discover …
    "acm_Arab": "Mesopotamian Arabic",
    "acq_Arab": "Ta’izzi‑Adeni Arabic",
    "aeb_Arab": "Tunisian Arabic",
    "ajp_Arab": "South Levantine Arabic",
    "aka_Latn": "Akan",
    "apc_Arab": "North Levantine Arabic",
    "ars_Arab": "Najdi Arabic",
    "arz_Arab": "Egyptian Arabic",
    "ast_Latn": "Asturian",
    "awa_Deva": "Awadhi",
    "ayr_Latn": "Aymara",
    "bam_Latn": "Bambara",
    "ban_Latn": "Balinese",
    "bel_Cyrl": "Belarusian",
    "bem_Latn": "Bemba",
    "bho_Deva": "Bhojpuri",
    "bos_Latn": "Bosnian",
    "bug_Latn": "Buginese",
    "bul_Cyrl": "Bulgarian",
    "cat_Latn": "Catalan",
    "ceb_Latn": "Cebuano",
    "ces_Latn": "Czech",
    "ckb_Arab": "Central Kurdish (Arabic script)",
    "crh_Latn": "Crimean Tatar",
    "cym_Latn": "Welsh",
    "dan_Latn": "Danish",
    "dik_Latn": "Southwestern Dinka",
    "ell_Grek": "Greek",
    "epo_Latn": "Esperanto",
    "eus_Latn": "Basque",
    "fin_Latn": "Finnish",
    "frr_Latn": "Northern Frisian",
    "fry_Latn": "Western Frisian",
    "gla_Latn": "Scottish Gaelic",
    "gle_Latn": "Irish",
    "guj_Gujr": "Gujarati",
    "hat_Latn": "Haitian Creole",
    "heb_Hebr": "Hebrew",
    "hrv_Latn": "Croatian",
    "ibo_Latn": "Igbo",
    "isl_Latn": "Icelandic",
    "ita_Latn": "Italian",
    "jav_Latn": "Javanese",
    "kan_Knda": "Kannada",
    "kat_Geor": "Georgian",
    "kir_Cyrl": "Kyrgyz",
    "khm_Khmr": "Khmer",
    "kin_Latn": "Kinyarwanda",
    "lao_Laoo": "Lao",
    "lav_Latn": "Latvian",
    "lin_Latn": "Lingala",
    "lit_Latn": "Lithuanian",
    "ltz_Latn": "Luxembourgish",
    "lug_Latn": "Ganda",
    "mkd_Cyrl": "Macedonian",
    "mlt_Latn": "Maltese",
    "mri_Latn": "Māori",
    "mya_Mymr": "Burmese",
    "nld_Latn": "Dutch",
    "nor_Latn": "Norwegian",
    "odi_Orya": "Odia",
    "pan_Guru": "Panjabi",
    "pol_Latn": "Polish",
    "por_Latn": "Portuguese",
    "ron_Latn": "Romanian",
    "srp_Cyrl": "Serbian",
    "sot_Latn": "Sesotho",
    "sun_Latn": "Sundanese",
    "swe_Latn": "Swedish",
    "tgl_Latn": "Filipino",
    "tam_Taml": "Tamil",
    "tel_Telu": "Telugu",
    "tha_Thai": "Thai",
    "tir_Ethi": "Tigrinya",
    "ukr_Cyrl": "Ukrainian",
    "uzb_Latn": "Uzbek (Latin script)",
    "wol_Latn": "Wolof",
    "xho_Latn": "Xhosa",
    "yor_Latn": "Yoruba",
    "zho_Hans": "Chinese (Simplified)",
    "zho_Hant": "Chinese (Traditional)"


}
